### ISSUE TITLE
Black screen if token vision is disabled and global illumination is active

### ISSUE THREAD

**Issue by jflevesque** [SteffanPoulsen/token-drag-visibility#1]
When I am on a scene with Token Vision: Off; Global Illumination: On; Fog Exploration: On; I can see the scene very well when I don't have a token selected. The moment I select a token, the scene becomes black. If I disable the module, it works as expected (whole scene is visible).

![BlackSceneWithTokenSelected](https://user-images.githubusercontent.com/10425571/83959120-8e31e380-a847-11ea-9a6d-d184f91efb3b.gif)

Foundry VTT: 0.6.2 (Electron)
Windows 10 Pro 64 bit

**Comment by SteffanPoulsen** [comment]
Hi jflevesque! sorry for the late reply, must have missed this - someone wrote me about the same issue a while ago on discord, and I updated the module with a fix.

Let me know if you still have any issues

**Comment by jflevesque** [comment]
Hi Steffan,

The update fixed the issue, thank you!
